/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_ShipmentBlotter_HeaderObjectPageObjectPage journey");

        opaTest("Navigate to ZC_ShipmentBlotter_HeaderObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_ShipmentBlotter_HeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_ShipmentBlotter_HeaderListGenerated.onTable().iCheckRows();
            When.onTheZC_ShipmentBlotter_HeaderListGenerated.onTable().iPressRow(0);

            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "HeaderCompletion" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "HeaderStops" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "HeaderTrackingStatus" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckNumberOfSections(5);
            When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iPressSectionIconTabFilterButton("GeneralSection");
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckSection({ section: "GeneralSection" });
            //When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iGoToSection({ section: "GeneralSection", subSection: "TransportFG" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckSubSection({ section: "TransportFG" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "TransportFG" }).iCheckField({ property: "Shipment" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "TransportFG" }).iCheckField({ property: "TransportPlanningPoint" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "TransportFG" }).iCheckField({ property: "Route" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "TransportFG" }).iCheckField({ property: "Driver" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "TransportFG" }).iCheckField({ property: "Vehicle" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "TransportFG" }).iCheckField({ property: "Trailer" });
            //When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iGoToSection({ section: "GeneralSection", subSection: "QuantitiesFG" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckSubSection({ section: "QuantitiesFG" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "QuantitiesFG" }).iCheckField({ property: "ActualCases" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "QuantitiesFG" }).iCheckField({ property: "ActualEaches" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "QuantitiesFG" }).iCheckField({ property: "ActualOthers" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "QuantitiesFG" }).iCheckField({ property: "NetWeight" });
            When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iPressSectionIconTabFilterButton("MilestoneSection");
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckSection({ section: "MilestoneSection" });
            //When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iGoToSection({ section: "MilestoneSection", subSection: "PlannedFG" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckSubSection({ section: "PlannedFG" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "PlannedFG" }).iCheckField({ property: "PlannedStartDate" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "PlannedFG" }).iCheckField({ property: "PlannedStartTime" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "PlannedFG" }).iCheckField({ property: "Timeprinted" });
            //When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iGoToSection({ section: "MilestoneSection", subSection: "ActualFG" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckSubSection({ section: "ActualFG" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "ActualFG" }).iCheckField({ property: "ActualCheckinDate" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "ActualFG" }).iCheckField({ property: "ActualCheckinTime" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "ActualFG" }).iCheckField({ property: "ActualStartDate" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "ActualFG" }).iCheckField({ property: "ActualStartTime" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "ActualFG" }).iCheckField({ property: "ActualEndtDate" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "ActualFG" }).iCheckField({ property: "ActualEndTime" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "ActualFG" }).iCheckField({ property: "LastStop" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "ActualFG" }).iCheckField({ property: "LastStopTime" });
            When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iPressSectionIconTabFilterButton("StatusSection");
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckSection({ section: "StatusSection" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "StatusSection" }).iCheckField({ property: "DeliveredinSequence" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "StatusSection" }).iCheckField({ property: "DeliveryTimeExceeded" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "StatusSection" }).iCheckField({ property: "FirstStopArrival" });
            When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iPressSectionIconTabFilterButton("TrackingSection");
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckSection({ section: "TrackingSection" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "TrackingSection" }).iCheckField({ property: "Tracking" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "TrackingSection" }).iCheckField({ property: "VehicleNoTracking" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onForm({ section: "TrackingSection" }).iCheckField({ property: "VehicleTypeTracking" });
            When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iPressSectionIconTabFilterButton("ShipmentItemsFacet");
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iCheckSection({ section: "ShipmentItemsFacet" });
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onTable({ property: "_ShipmentItem" }).iCheckColumns(undefined, {"Shipment":{"header":"Shipment"},"TransportPlanningPoint":{"header":"Transportation Point"},"Stop":{"header":"Stop"},"Delivery":{"header":"Delivery"},"ShipToParty":{"header":"Ship-to Party"},"Shiptoname":{"header":"Ship-to Party Name"},"Shiptostreet":{"header":"Ship-to Party Street"},"Shiptocity":{"header":"Ship-to Party City"},"Shiptotelephone":{"header":"Ship-to Party Telephone"},"Shiptopostalcode":{"header":"Ship-to Party Postal"},"ActualCases":{"header":"Cases"},"ActualEaches":{"header":"Eaches"},"NetWeight":{"header":"Net Weight(LB)"},"ActualOthers":{"header":"Other UoM"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});