/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_ShipmentBlotter_ItemObjectPageObjectPage journey");

        opaTest("Navigate to ZC_ShipmentBlotter_ItemObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_ShipmentBlotter_HeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_ShipmentBlotter_HeaderListGenerated.onTable().iCheckRows();
            When.onTheZC_ShipmentBlotter_HeaderListGenerated.onTable().iPressRow(0);

            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.iSeeThisPage();
            Then.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onTable({ property: "_ShipmentItem" }).iCheckRows();
            When.onTheZC_ShipmentBlotter_HeaderObjectPageGenerated.onTable({ property: "_ShipmentItem" }).iPressRow(0);

            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.iCheckSection({ section: "Delivery" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "Shipment" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "TransportPlanningPoint" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "Stop" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "Delivery" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "ShipToParty" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "Shiptoname" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "Shiptostreet" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "Shiptocity" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "Shiptotelephone" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "Shiptopostalcode" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "ActualCases" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "ActualEaches" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "NetWeight" });
            Then.onTheZC_ShipmentBlotter_ItemObjectPageGenerated.onForm({ section: "Delivery" }).iCheckField({ property: "ActualOthers" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});