/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_MaterialVerifyOneNoteObjectPageObjectPage journey");

        opaTest("Navigate to ZC_MaterialVerifyOneNoteObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_MaterialVerifyOneNoteListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_MaterialVerifyOneNoteListGenerated.onTable().iCheckRows();
            When.onTheZC_MaterialVerifyOneNoteListGenerated.onTable().iPressRow(0);

            Then.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iCheckNumberOfSections(4);
            When.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iPressSectionIconTabFilterButton("COLLFAC1");
            Then.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iCheckSection({ section: "COLLFAC1" });
            When.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iPressSectionIconTabFilterButton("COLLFAC2");
            Then.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iCheckSection({ section: "COLLFAC2" });
            When.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iPressSectionIconTabFilterButton("COLLFAC3");
            Then.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iCheckSection({ section: "COLLFAC3" });
            When.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iPressSectionIconTabFilterButton("COLLFAC4");
            Then.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iCheckSection({ section: "COLLFAC4" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});