/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_MaterialVerifyOneNoteListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_MaterialVerifyOneNoteListGenerated.iSeeThisPage();
        });


        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZC_MaterialVerifyOneNoteListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZC_MaterialVerifyOneNoteListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZC_MaterialVerifyOneNoteListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_MaterialVerifyOneNoteListGenerated.onTable().iCheckColumns(undefined, {"Matnr":{"header":"Material"},"MaterialName":{"header":"Material Description"},"Imageitem":{"header":"Line Id"},"Weight":{"header":"Weight"},"DateofManufacture":{"header":"Date"},"WeightUnit":{"header":"Weight Unit"},"LotNumber":{"header":"Lot Number"},"ItemNumber":{"header":"Item Number"},"BarcodeValue":{"header":"Barcode"},"Znote":{"header":"Note"},"ImageUrl":{"header":"Image Internal Url"},"AttachmentUrl":{"header":"Image Preview"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZC_MaterialVerifyOneNoteListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheZC_MaterialVerifyOneNoteListGenerated.onTable().iCheckRows();

            When.onTheZC_MaterialVerifyOneNoteListGenerated.onTable().iPressRow(0);
            Then.onTheZC_MaterialVerifyOneNoteObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});