/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_ORDERCUTOFFQV1ListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_ORDERCUTOFFQV1ListGenerated.iSeeThisPage();
        });


        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZC_ORDERCUTOFFQV1ListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZC_ORDERCUTOFFQV1ListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZC_ORDERCUTOFFQV1ListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_ORDERCUTOFFQV1ListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"SalesLeadName":{"header":"SalesLead Name"},"SoldToParty":{"header":"Sold To Party"},"CreationDate":{"header":"Creation Date"},"CreationTime":{"header":"Creation Time"},"SalesDocument":{"header":"Sales Document"},"SoldToPartyName":{"header":"Sold To Party Name"},"Counter":{"header":"Counter"},"NextDayDate":{"header":"Next Delivery Date"},"Route":{"header":"Route"},"RequestedDeliveryDate":{"header":"Delivery Date"},"DistributionChannel":{"header":"Distribution Channel"},"OrganizationDivision":{"header":"Division"},"ShipToParty":{"header":"Ship To Party"},"ShipToPartyName":{"header":"Ship To Party Name"},"SalesLead":{"header":"SalesLead"},"SalesOrganization":{"header":"Sales Organization"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheZC_ORDERCUTOFFQV1ListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_ORDERCUTOFFQV1ListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheZC_ORDERCUTOFFQV1ListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheZC_ORDERCUTOFFQV1ObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});